export const cars = [
  {
    id: 1,
    name: "Ford Ranger",
    price: "$62,593",
    image: "/cars/ford-ranger.png",
    badge: "Best Seller",
    rating: 4.5,
    features: ["4x4", "Diesel", "Automatic"],
    category: "suv",
  },
  {
    id: 2,
    name: "Toyota RAV4",
    price: "$58,718",
    image: "/cars/rav-4.png",
    badge: "Top SUV",
    rating: 4.7,
    features: ["Hybrid", "Automatic", "5 Seats"],
    category: "suv",
  },
  {
    id: 3,
    name: "Toyota HiLux",
    price: "$53,499",
    image: "/cars/Toyota-hilux.png",
    badge: "Top Ute",
    rating: 4.6,
    features: ["4x4", "Diesel", "Manual"],
    category: "ute",
  },
  {
    id: 4,
    name: "Mitsubishi Outlander",
    price: "$27,613",
    image: "/cars/mitsubushi-outlander.png",
    badge: "Popular Choice",
    rating: 4.3,
    features: ["Hybrid", "Automatic", "7 Seats"],
    category: "suv",
  },
  {
    id: 5,
    name: "Ford Everest",
    price: "$26,494",
    image: "/cars/ford-everest.png",
    badge: "Top SUV",
    rating: 4.4,
    features: ["4x4", "Diesel", "Automatic"],
    category: "suv",
  },
  {
    id: 6,
    name: "Isuzu Ute D-Max",
    price: "$24,031",
    image: "/cars/Isuzu-Ute-D-Max.png",
    badge: "Durable Build",
    rating: 4.2,
    features: ["4x4", "Diesel", "Manual"],
    category: "ute",
  },
  {
    id: 7,
    name: "Toyota Corolla",
    price: "$24,027",
    image: "/cars/toyota-camry.png",
    badge: "Compact Favorite",
    rating: 4.1,
    features: ["Petrol", "Automatic", "5 Seats"],
    category: "sedan",
  },
  {
    id: 8,
    name: "Mazda CX-5",
    price: "$22,835",
    image: "/cars/mazda-cx-5.png",
    badge: "Top Crossover",
    rating: 4.5,
    features: ["Petrol", "Automatic", "5 Seats"],
    category: "suv",
  },
  {
    id: 9,
    name: "MG ZS",
    price: "$22,629",
    image: "/cars/mg-zs.png",
    badge: "Affordable SUV",
    rating: 4.0,
    features: ["Petrol", "Automatic", "5 Seats"],
    category: "suv",
  },
  {
    id: 10,
    name: "Kia Sportage",
    price: "$22,210",
    image: "/cars/kia-sportage.png",
    badge: "Stylish SUV",
    rating: 4.3,
    features: ["Petrol", "Automatic", "5 Seats"],
    category: "suv",
  },
  {
    id: 11,
    name: "Tesla Model Y",
    price: "$21,253",
    image: "/cars/tesla-model-y.png",
    badge: "Top EV",
    rating: 4.8,
    features: ["Electric", "Automatic", "5 Seats"],
    category: "ev",
  },
  {
    id: 12,
    name: "Hyundai Tucson",
    price: "$19,061",
    image: "/cars/hyundai-tucson.png",
    badge: "Reliable SUV",
    rating: 4.2,
    features: ["Petrol", "Automatic", "5 Seats"],
    category: "suv",
  },
  {
    id: 13,
    name: "Mazda CX-3",
    price: "$18,461",
    image: "/cars/mazda-cx-3.png",
    badge: "Compact SUV",
    rating: 4.1,
    features: ["Petrol", "Automatic", "5 Seats"],
    category: "suv",
  },
  {
    id: 14,
    name: "Mitsubishi Triton",
    price: "$18,077",
    image: "/cars/mitsubishi-triton.png",
    badge: "Top Ute",
    rating: 4.0,
    features: ["4x4", "Diesel", "Manual"],
    category: "ute",
  },
  {
    id: 15,
    name: "Isuzu Ute MU-X",
    price: "$17,978",
    image: "/cars/sport-suv.png",
    badge: "Family SUV",
    rating: 4.3,
    features: ["4x4", "Diesel", "7 Seats"],
    category: "suv",
  },
  {
    id: 16,
    name: "Nissan X-Trail",
    price: "$17,494",
    image: "/cars/nissan-x-trail.png",
    badge: "Versatile SUV",
    rating: 4.2,
    features: ["Petrol", "Automatic", "5 Seats"],
    category: "suv",
  },
  {
    id: 17,
    name: "Hyundai Kona",
    price: "$17,374",
    image: "/cars/hyundai-kona.png",
    badge: "Compact SUV",
    rating: 4.1,
    features: ["Petrol", "Automatic", "5 Seats"],
    category: "suv",
  },
  {
    id: 18,
    name: "Kia Cerato",
    price: "$15,502",
    image: "/cars/kia-cerato.png",
    badge: "Affordable Sedan",
    rating: 4.0,
    features: ["Petrol", "Automatic", "5 Seats"],
    category: "sedan",
  },
  {
    id: 19,
    name: "Toyota Camry",
    price: "$15,401",
    image: "/cars/toyota-camry.png",
    badge: "Reliable Sedan",
    rating: 4.3,
    features: ["Hybrid", "Automatic", "5 Seats"],
    category: "sedan",
  },
  {
    id: 20,
    name: "Toyota Landcruiser 300",
    price: "$25,000",
    image: "/cars/toyota-landcruiser.png",
    badge: "Luxury SUV",
    rating: 4.6,
    features: ["4x4", "Diesel", "7 Seats"],
    category: "suv",
  },
];